name: own-deepu
on: push
env:
    Node_Version: 18
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        
        - name: set up nodejs
          uses: actions/set-up-node@v4
          with:
            version: ${{env.Node_Version}}
            cache: npm

    deploy-to-docker:
        runs-on: ubuntu-latest
        steps:
        - name: login to docker
          run: echo "${{ secrets.Docker_Password }}" | docker login -u "${{ secrets.Docker_Username}}"
          